improved tiosetup

diff --git a/misc/tiopull b/misc/tiopull
--- a/misc/tiopull
+++ b/misc/tiopull
@@ -1,13 +1,19 @@
-#!/bin/bash 
+#!/bin/bash
+
+if (($# == 0)); then
+	printf "$0: missing parameter\nUsage: tiopull {-a | LANGUAGE...}\n"
+	exit 1
+fi
 
 cd /opt
+echo -n 'Updating tiosetup... '
+git -C tiosetup pull
 
-if [[ "$1" == -a ]]; then
-  /opt/tiosetup/run-scripts /opt/tiosetup/languages
+if [[ "$*" == -a ]]; then
+	tiosetup/run-scripts tiosetup/languages
 else
-  if [[ "$1" ]]; then
-    /opt/tiosetup/languages/$1
-  else
-    echo 'Missing parameter. Usage: tiopull language|-a'
-  fi
+	for language in $*; do
+		printf "\nInstalling/updating $language.\n"
+		tiosetup/languages/$language
+	done
 fi
